//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kayit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kayit
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Ad alaný boþ geçilemez.")]
        [Display(Name = "Adýnýz")]
        public string ad { get; set; }

        [Required(ErrorMessage = "Soyadý alaný boþ geçilemez.")]
        [Display(Name = "Soyadýnýz")]
        public string soyad { get; set; }

        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
            ErrorMessage = "Lütfen uygun formatta e-mail adresi giriniz.")]
        [Required(ErrorMessage = "Email alaný boþ geçilemez.")]
        [Display(Name = "Email")]
        public string email { get; set; }

        [MinLength(8, ErrorMessage = "Minimum 8 karakterlik giriþ yapmalýsýnýz")]
        [Required(ErrorMessage = "Þifre alaný boþ geçilemez.")]
        [Display(Name = "Þifre")]
        public string sifre { get; set; }
    }
}
